# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'HikingSocialApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Lynx Framework
  pod 'lynx', '~> 0.13.0'

  # 高德地图
  pod 'AMap3DMap', '~> 9.7.0'
  pod 'AMapSearch', '~> 9.7.0'
  pod 'AMapLocation', '~> 2.9.0'

  target 'HikingSocialAppTests' do
    inherit! :search_paths
  end

  target 'HikingSocialAppUITests' do
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
